# coding: utf-8

"""
    Mtmai API

    The Mtmai API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mtmai.clients.rest.models.state_type import StateType
from typing import Optional, Set
from typing_extensions import Self

class AgStateUpsert(BaseModel):
    """
    AgStateUpsert
    """ # noqa: E501
    version: Optional[StrictStr] = '1.0.0'
    type: StateType
    component_id: StrictStr = Field(alias="componentId")
    chat_id: StrictStr = Field(alias="chatId")
    topic: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    state: Dict[str, Any]
    state_id: Optional[StrictStr] = Field(default=None, alias="stateId")
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    __properties: ClassVar[List[str]] = ["version", "type", "componentId", "chatId", "topic", "source", "state", "stateId", "tenantId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgStateUpsert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgStateUpsert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version") if obj.get("version") is not None else '1.0.0',
            "type": obj.get("type"),
            "componentId": obj.get("componentId"),
            "chatId": obj.get("chatId"),
            "topic": obj.get("topic"),
            "source": obj.get("source"),
            "state": obj.get("state"),
            "stateId": obj.get("stateId"),
            "tenantId": obj.get("tenantId")
        })
        return _obj


