# coding: utf-8

"""
    Mtmai API

    The Mtmai API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FlowNames(str, Enum):
    """
    FlowNames
    """

    """
    allowed enum values
    """
    SYS = 'sys'
    TENANT = 'tenant'
    ASSISTANT = 'assistant'
    AG = 'ag'
    BROWSER = 'browser'
    SMOLA = 'smola'
    TEAM = 'team'
    COM = 'com'
    PLATFORM_ACCOUNT_LOGIN = 'platform_account_login'
    PLATFORM_ACCOUNT_FOLLOW = 'platform_account_follow'
    RESOURCE = 'resource'
    INSTAGRAM = 'instagram'
    USER = 'user'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FlowNames from a JSON string"""
        return cls(json.loads(json_str))


