[project]
name = "mtworker"
version = "0.1.0"
dependencies = [
    "pydantic-settings",
    "python-dotenv>=1.0.1",

]

description = "mtworker"
authors = [{ name = "mtworker", email = "mtworker@gmail.com" }]
license = "MIT"
readme = "README.md"
keywords = ["scrapegraph", "llm"]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12,<4.0"


[project.scripts]
mtworker = "mtworker.main:app"

[dependency-groups]
dev = [
    "aiofiles>=0.8.0",
    "grpcio>=1.70.0",
    "aiofiles>=0.8.0",
    "tokencost~=0.1.16",
    "build~=1.2.2",
    "pytest~=8.3.3",
    "pytest-asyncio~=0.24.0",
    "matplotlib>=3.10.0",
    "gradio>=5.12.0",
    "prometheus-client>=0.21.1",
    "pytest-watcher>=0.4.3",
]

media = [
    "moviepy>=2.2.1",
    "ffmpeg-python>=0.2.0",
    "pydub>=0.25.1",
    "pytube>=12.0.0",
    "pytubefix>=8.13.1",
    "youtube-transcript-api>=1.0.3",
    "m3u8>=6.0.0",
    "edge-tts>=6.1.19",
    "python-pptx>=1.0.2",
]

# Group 1: Other Language Models
other-language-models = [
    "langchain-google-vertexai>=1.0.7",
    "langchain-fireworks>=0.1.3",
    "langchain-groq>=0.1.3",
    "langchain-anthropic>=0.1.11",
    "langchain-huggingface>=0.0.3",
    # "langchain-nvidia-ai-endpoints>=0.1.6",
    "langchain_together>=0.2.0",

]

# Group 2: More Semantic Options
more-semantic-options = ["graphviz>=0.20.3"]

# Group 3: More Browser Options
more-browser-options = ["browserbase>=0.3.0"]

# Group 4: Surya Library
screenshot_scraper = [
    # "surya-ocr>=0.5.0",
    "matplotlib>=3.7.2",
    "ipywidgets>=8.1.0",
    # "pillow>=10.4.0",
]

[build-system]
requires = ["hatchling>=1.0.0", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["mtworker"]
exclude = ["tests/**", ".vol/**", "__pycache__/**"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["mtmai"]

[tool.hatch.build.targets.sdist]
include = ["mtworker", "pyproject.toml", "README.md", "LICENSE"]
packages = ["mtworker"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
quantstats = { git = "https://github.com/PowerInsight/quantstats.git" }
