disallowAdditionalPropertiesIfNotPresent: "true"
enumClassPrefix: "true"
generateInterfaces: "true"
generateMarshalJSON: "true"
hideGenerationTimestamp: "false"
isGoSubmodule: "true"
packageName: "mtmai.clients.rest"
packageVersion: "v11.0.0"
prependFormOrBodyParameters: "true"
structPrefix: "true"
useOneOfDiscriminatorLookup: "true"
withAWSV4Signature: "false"
withGoMod: "true"
withXml: "true"
