# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/protoc-gen-connecpy.  DO NOT EDIT!
# source: mtm/sppb/ag.proto

from typing import Any, Protocol, Union

import httpx

from connecpy.async_client import AsyncConnecpyClient
from connecpy.base import Endpoint
from connecpy.server import ConnecpyServer
from connecpy.client import ConnecpyClient
from connecpy.context import ClientContext, ServiceContext

import mtm.sppb.ag_pb2 as _pb2

from google.protobuf import symbol_database

_sym_db = symbol_database.Default()


class AgService(Protocol):
    async def TeamGet(self, req: _pb2.TeamGetRequest, ctx: ServiceContext) -> _pb2.TeamGetReply: ...
    async def Greet(self, req: _pb2.GreetRequest, ctx: ServiceContext) -> _pb2.GreetResponse: ...
    async def Greet2(self, req: _pb2.GreetRequest, ctx: ServiceContext) -> _pb2.GreetResponse: ...
    async def GetComponent(self, req: _pb2.GetComponentRequest, ctx: ServiceContext) -> _pb2.GetComponentReply: ...


class AgServiceServer(ConnecpyServer):
    def __init__(self, *, service: AgService, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/mtmai.mtm.sppb.AgService"
        self._endpoints = {
            "TeamGet": Endpoint[_pb2.TeamGetRequest, _pb2.TeamGetReply](
                service_name="AgService",
                name="TeamGet",
                function=getattr(service, "TeamGet"),
                input=_pb2.TeamGetRequest,
                output=_pb2.TeamGetReply,
                allowed_methods=("POST",),
            ),
            "Greet": Endpoint[_pb2.GreetRequest, _pb2.GreetResponse](
                service_name="AgService",
                name="Greet",
                function=getattr(service, "Greet"),
                input=_pb2.GreetRequest,
                output=_pb2.GreetResponse,
                allowed_methods=("POST",),
            ),
            "Greet2": Endpoint[_pb2.GreetRequest, _pb2.GreetResponse](
                service_name="AgService",
                name="Greet2",
                function=getattr(service, "Greet2"),
                input=_pb2.GreetRequest,
                output=_pb2.GreetResponse,
                allowed_methods=("POST",),
            ),
            "GetComponent": Endpoint[_pb2.GetComponentRequest, _pb2.GetComponentReply](
                service_name="AgService",
                name="GetComponent",
                function=getattr(service, "GetComponent"),
                input=_pb2.GetComponentRequest,
                output=_pb2.GetComponentReply,
                allowed_methods=("POST",),
            ),
        }

    def serviceName(self):
        return "mtmai.mtm.sppb.AgService"


class AgServiceSync(Protocol):
    def TeamGet(self, req: _pb2.TeamGetRequest, ctx: ServiceContext) -> _pb2.TeamGetReply: ...
    def Greet(self, req: _pb2.GreetRequest, ctx: ServiceContext) -> _pb2.GreetResponse: ...
    def Greet2(self, req: _pb2.GreetRequest, ctx: ServiceContext) -> _pb2.GreetResponse: ...
    def GetComponent(self, req: _pb2.GetComponentRequest, ctx: ServiceContext) -> _pb2.GetComponentReply: ...


class AgServiceServerSync(ConnecpyServer):
    def __init__(self, *, service: AgServiceSync, server_path_prefix=""):
        super().__init__()
        self._prefix = f"{server_path_prefix}/mtmai.mtm.sppb.AgService"
        self._endpoints = {
            "TeamGet": Endpoint[_pb2.TeamGetRequest, _pb2.TeamGetReply](
                service_name="AgService",
                name="TeamGet",
                function=getattr(service, "TeamGet"),
                input=_pb2.TeamGetRequest,
                output=_pb2.TeamGetReply,
                allowed_methods=("POST",),
            ),
            "Greet": Endpoint[_pb2.GreetRequest, _pb2.GreetResponse](
                service_name="AgService",
                name="Greet",
                function=getattr(service, "Greet"),
                input=_pb2.GreetRequest,
                output=_pb2.GreetResponse,
                allowed_methods=("POST",),
            ),
            "Greet2": Endpoint[_pb2.GreetRequest, _pb2.GreetResponse](
                service_name="AgService",
                name="Greet2",
                function=getattr(service, "Greet2"),
                input=_pb2.GreetRequest,
                output=_pb2.GreetResponse,
                allowed_methods=("POST",),
            ),
            "GetComponent": Endpoint[_pb2.GetComponentRequest, _pb2.GetComponentReply](
                service_name="AgService",
                name="GetComponent",
                function=getattr(service, "GetComponent"),
                input=_pb2.GetComponentRequest,
                output=_pb2.GetComponentReply,
                allowed_methods=("POST",),
            ),
        }

    def serviceName(self):
        return "mtmai.mtm.sppb.AgService"


class AgServiceClient(ConnecpyClient):
    def TeamGet(
        self,
        *,
        request: _pb2.TeamGetRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.TeamGetReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/TeamGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.TeamGetReply,
            method=method,
            **kwargs,
        )

    def Greet(
        self,
        *,
        request: _pb2.GreetRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.GreetResponse:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/Greet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GreetResponse,
            method=method,
            **kwargs,
        )

    def Greet2(
        self,
        *,
        request: _pb2.GreetRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.GreetResponse:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/Greet2",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GreetResponse,
            method=method,
            **kwargs,
        )

    def GetComponent(
        self,
        *,
        request: _pb2.GetComponentRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        **kwargs,
    ) -> _pb2.GetComponentReply:
        method = "POST"
        return self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/GetComponent",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GetComponentReply,
            method=method,
            **kwargs,
        )


class AsyncAgServiceClient(AsyncConnecpyClient):
    async def TeamGet(
        self,
        *,
        request: _pb2.TeamGetRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.TeamGetReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/TeamGet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.TeamGetReply,
            method=method,
            session=session,
            **kwargs,
        )

    async def Greet(
        self,
        *,
        request: _pb2.GreetRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.GreetResponse:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/Greet",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GreetResponse,
            method=method,
            session=session,
            **kwargs,
        )

    async def Greet2(
        self,
        *,
        request: _pb2.GreetRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.GreetResponse:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/Greet2",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GreetResponse,
            method=method,
            session=session,
            **kwargs,
        )

    async def GetComponent(
        self,
        *,
        request: _pb2.GetComponentRequest,
        ctx: ClientContext,
        server_path_prefix: str = "",
        session: Union[httpx.AsyncClient, None] = None,
        **kwargs,
    ) -> _pb2.GetComponentReply:
        method = "POST"
        return await self._make_request(
            url=f"{server_path_prefix}/mtmai.mtm.sppb.AgService/GetComponent",
            ctx=ctx,
            request=request,
            response_obj=_pb2.GetComponentReply,
            method=method,
            session=session,
            **kwargs,
        )
