# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mtm/sppb/git.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mtm/sppb/git.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mtm.sppb import mtm_pb2 as mtm_dot_sppb_dot_mtm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12mtm/sppb/git.proto\x12\x0emtmai.mtm.sppb\x1a\x12mtm/sppb/mtm.proto\"\x1c\n\nGitPullReq\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n\x0bGitSetupReq\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\r\n\x0bGitSetupRes\"\x0c\n\nGitPullRes\"!\n\tGitGetReq\x12\x14\n\x05slugs\x18\x01 \x01(\tR\x05slugs\"\x19\n\x07GitInfo\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n\x0bGitStartReq\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\r\n\x0bGitStartRes\"\x1c\n\nGitStopReq\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x0c\n\nGitStopRes2\xb3\x03\n\nGitService\x12K\n\x07GitList\x12\x1e.mtmai.mtm.sppb.CommontListReq\x1a\x1e.mtmai.mtm.sppb.CommontListRes\"\x00\x12>\n\x06GitGet\x12\x19.mtmai.mtm.sppb.GitGetReq\x1a\x17.mtmai.mtm.sppb.GitInfo\"\x00\x12\x43\n\x07GitPull\x12\x1a.mtmai.mtm.sppb.GitPullReq\x1a\x1a.mtmai.mtm.sppb.GitPullRes\"\x00\x12\x46\n\x08GitSetup\x12\x1b.mtmai.mtm.sppb.GitSetupReq\x1a\x1b.mtmai.mtm.sppb.GitSetupRes\"\x00\x12\x46\n\x08GitStart\x12\x1b.mtmai.mtm.sppb.GitStartReq\x1a\x1b.mtmai.mtm.sppb.GitStartRes\"\x00\x12\x43\n\x07GitStop\x12\x1a.mtmai.mtm.sppb.GitStopReq\x1a\x1a.mtmai.mtm.sppb.GitStopRes\"\x00\x42\xa1\x01\n\x12\x63om.mtmai.mtm.sppbB\x08GitProtoP\x01Z\'github.com/codeh007/gomtm/mtm/sppb;sppb\xa2\x02\x03MMS\xaa\x02\x0eMtmai.Mtm.Sppb\xca\x02\x0eMtmai\\Mtm\\Sppb\xe2\x02\x1aMtmai\\Mtm\\Sppb\\GPBMetadata\xea\x02\x10Mtmai::Mtm::Sppbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mtm.sppb.git_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.mtmai.mtm.sppbB\010GitProtoP\001Z\'github.com/codeh007/gomtm/mtm/sppb;sppb\242\002\003MMS\252\002\016Mtmai.Mtm.Sppb\312\002\016Mtmai\\Mtm\\Sppb\342\002\032Mtmai\\Mtm\\Sppb\\GPBMetadata\352\002\020Mtmai::Mtm::Sppb'
  _globals['_GITPULLREQ']._serialized_start=58
  _globals['_GITPULLREQ']._serialized_end=86
  _globals['_GITSETUPREQ']._serialized_start=88
  _globals['_GITSETUPREQ']._serialized_end=117
  _globals['_GITSETUPRES']._serialized_start=119
  _globals['_GITSETUPRES']._serialized_end=132
  _globals['_GITPULLRES']._serialized_start=134
  _globals['_GITPULLRES']._serialized_end=146
  _globals['_GITGETREQ']._serialized_start=148
  _globals['_GITGETREQ']._serialized_end=181
  _globals['_GITINFO']._serialized_start=183
  _globals['_GITINFO']._serialized_end=208
  _globals['_GITSTARTREQ']._serialized_start=210
  _globals['_GITSTARTREQ']._serialized_end=239
  _globals['_GITSTARTRES']._serialized_start=241
  _globals['_GITSTARTRES']._serialized_end=254
  _globals['_GITSTOPREQ']._serialized_start=256
  _globals['_GITSTOPREQ']._serialized_end=284
  _globals['_GITSTOPRES']._serialized_start=286
  _globals['_GITSTOPRES']._serialized_end=298
  _globals['_GITSERVICE']._serialized_start=301
  _globals['_GITSERVICE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
