# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mtm.sppb import workflows_pb2 as mtm_dot_sppb_dot_workflows__pb2


class WorkflowServiceStub(object):
    """WorkflowService represents a set of RPCs for managing workflows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutWorkflow = channel.unary_unary(
                '/mtmai.mtm.sppb.WorkflowService/PutWorkflow',
                request_serializer=mtm_dot_sppb_dot_workflows__pb2.PutWorkflowRequest.SerializeToString,
                response_deserializer=mtm_dot_sppb_dot_workflows__pb2.WorkflowVersion.FromString,
                _registered_method=True)
        self.ScheduleWorkflow = channel.unary_unary(
                '/mtmai.mtm.sppb.WorkflowService/ScheduleWorkflow',
                request_serializer=mtm_dot_sppb_dot_workflows__pb2.ScheduleWorkflowRequest.SerializeToString,
                response_deserializer=mtm_dot_sppb_dot_workflows__pb2.WorkflowVersion.FromString,
                _registered_method=True)
        self.TriggerWorkflow = channel.unary_unary(
                '/mtmai.mtm.sppb.WorkflowService/TriggerWorkflow',
                request_serializer=mtm_dot_sppb_dot_workflows__pb2.TriggerWorkflowRequest.SerializeToString,
                response_deserializer=mtm_dot_sppb_dot_workflows__pb2.TriggerWorkflowResponse.FromString,
                _registered_method=True)
        self.BulkTriggerWorkflow = channel.unary_unary(
                '/mtmai.mtm.sppb.WorkflowService/BulkTriggerWorkflow',
                request_serializer=mtm_dot_sppb_dot_workflows__pb2.BulkTriggerWorkflowRequest.SerializeToString,
                response_deserializer=mtm_dot_sppb_dot_workflows__pb2.BulkTriggerWorkflowResponse.FromString,
                _registered_method=True)
        self.PutRateLimit = channel.unary_unary(
                '/mtmai.mtm.sppb.WorkflowService/PutRateLimit',
                request_serializer=mtm_dot_sppb_dot_workflows__pb2.PutRateLimitRequest.SerializeToString,
                response_deserializer=mtm_dot_sppb_dot_workflows__pb2.PutRateLimitResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer(object):
    """WorkflowService represents a set of RPCs for managing workflows.
    """

    def PutWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScheduleWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkTriggerWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutRateLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.PutWorkflow,
                    request_deserializer=mtm_dot_sppb_dot_workflows__pb2.PutWorkflowRequest.FromString,
                    response_serializer=mtm_dot_sppb_dot_workflows__pb2.WorkflowVersion.SerializeToString,
            ),
            'ScheduleWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleWorkflow,
                    request_deserializer=mtm_dot_sppb_dot_workflows__pb2.ScheduleWorkflowRequest.FromString,
                    response_serializer=mtm_dot_sppb_dot_workflows__pb2.WorkflowVersion.SerializeToString,
            ),
            'TriggerWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerWorkflow,
                    request_deserializer=mtm_dot_sppb_dot_workflows__pb2.TriggerWorkflowRequest.FromString,
                    response_serializer=mtm_dot_sppb_dot_workflows__pb2.TriggerWorkflowResponse.SerializeToString,
            ),
            'BulkTriggerWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkTriggerWorkflow,
                    request_deserializer=mtm_dot_sppb_dot_workflows__pb2.BulkTriggerWorkflowRequest.FromString,
                    response_serializer=mtm_dot_sppb_dot_workflows__pb2.BulkTriggerWorkflowResponse.SerializeToString,
            ),
            'PutRateLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.PutRateLimit,
                    request_deserializer=mtm_dot_sppb_dot_workflows__pb2.PutRateLimitRequest.FromString,
                    response_serializer=mtm_dot_sppb_dot_workflows__pb2.PutRateLimitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mtmai.mtm.sppb.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mtmai.mtm.sppb.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService(object):
    """WorkflowService represents a set of RPCs for managing workflows.
    """

    @staticmethod
    def PutWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtm.sppb.WorkflowService/PutWorkflow',
            mtm_dot_sppb_dot_workflows__pb2.PutWorkflowRequest.SerializeToString,
            mtm_dot_sppb_dot_workflows__pb2.WorkflowVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScheduleWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtm.sppb.WorkflowService/ScheduleWorkflow',
            mtm_dot_sppb_dot_workflows__pb2.ScheduleWorkflowRequest.SerializeToString,
            mtm_dot_sppb_dot_workflows__pb2.WorkflowVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtm.sppb.WorkflowService/TriggerWorkflow',
            mtm_dot_sppb_dot_workflows__pb2.TriggerWorkflowRequest.SerializeToString,
            mtm_dot_sppb_dot_workflows__pb2.TriggerWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkTriggerWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtm.sppb.WorkflowService/BulkTriggerWorkflow',
            mtm_dot_sppb_dot_workflows__pb2.BulkTriggerWorkflowRequest.SerializeToString,
            mtm_dot_sppb_dot_workflows__pb2.BulkTriggerWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutRateLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mtmai.mtm.sppb.WorkflowService/PutRateLimit',
            mtm_dot_sppb_dot_workflows__pb2.PutRateLimitRequest.SerializeToString,
            mtm_dot_sppb_dot_workflows__pb2.PutRateLimitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
