# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mtmai/mtmpb/flowevents.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'mtmai/mtmpb/flowevents.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cmtmai/mtmpb/flowevents.proto\x12\x0bmtmai.mtmpb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/descriptor.proto\"\x86\x01\n\x0b\x43hatMessage\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n\x07\x63ontent\x18\x02 \x01(\tR\x07\x63ontent\x12\x12\n\x04role\x18\x03 \x01(\tR\x04role\x12\x39\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\":\n\x0e\x45ventEmbedding\x12\x12\n\x04\x63oll\x18\x01 \x01(\tR\x04\x63oll\x12\x14\n\x05texts\x18\x02 \x03(\tR\x05textsB\x98\x01\n\x0f\x63om.mtmai.mtmpbB\x0f\x46loweventsProtoP\x01Z\'github.com/codeh007/gomtm/mtm/sppb;sppb\xa2\x02\x03MMX\xaa\x02\x0bMtmai.Mtmpb\xca\x02\x0bMtmai\\Mtmpb\xe2\x02\x17Mtmai\\Mtmpb\\GPBMetadata\xea\x02\x0cMtmai::Mtmpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mtmai.mtmpb.flowevents_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.mtmai.mtmpbB\017FloweventsProtoP\001Z\'github.com/codeh007/gomtm/mtm/sppb;sppb\242\002\003MMX\252\002\013Mtmai.Mtmpb\312\002\013Mtmai\\Mtmpb\342\002\027Mtmai\\Mtmpb\\GPBMetadata\352\002\014Mtmai::Mtmpb'
  _globals['_CHATMESSAGE']._serialized_start=113
  _globals['_CHATMESSAGE']._serialized_end=247
  _globals['_EVENTEMBEDDING']._serialized_start=249
  _globals['_EVENTEMBEDDING']._serialized_end=307
# @@protoc_insertion_point(module_scope)
